#ifndef _SRC_RPC_PROTOCOL_PROTOBUF_PLUGIN_BASIC_DECL_GENERATOR_H_
#define _SRC_RPC_PROTOCOL_PROTOBUF_PLUGIN_BASIC_DECL_GENERATOR_H_

#include "google/protobuf/descriptor.h"

#include "code_writer.h"

namespace tinyRPC::protobuf::plugin {

// This class generates classes that behaves in the same way as of those
// generated by `cc_generic_services = true;`.
class BasicDeclGenerator {
 public:
  void GenerateService(const google::protobuf::FileDescriptor* file,
                       const google::protobuf::ServiceDescriptor* service,
                       CodeWriter* writer);

  void GenerateStub(const google::protobuf::FileDescriptor* file,
                    const google::protobuf::ServiceDescriptor* service,
                    CodeWriter* writer);
};

}  // namespace tinyRPC::protobuf::plugin

#endif  
