// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_options.proto

#include "rpc_options.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace flare {
}  // namespace flare
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_rpc_5foptions_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_rpc_5foptions_2eproto = nullptr;
const uint32_t TableStruct_rpc_5foptions_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_rpc_5foptions_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021rpc_options.proto\022\005flare\032 google/proto"
  "buf/descriptor.proto:>\n\025max_queueing_del"
  "ay_ms\022\036.google.protobuf.MethodOptions\030\373U"
  " \001(\005:=\n\024max_ongoing_requests\022\036.google.pr"
  "otobuf.MethodOptions\030\374U \001(\005"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_rpc_5foptions_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::_pbi::once_flag descriptor_table_rpc_5foptions_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_rpc_5foptions_2eproto = {
    false, false, 187, descriptor_table_protodef_rpc_5foptions_2eproto,
    "rpc_options.proto",
    &descriptor_table_rpc_5foptions_2eproto_once, descriptor_table_rpc_5foptions_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_rpc_5foptions_2eproto::offsets,
    nullptr, file_level_enum_descriptors_rpc_5foptions_2eproto,
    file_level_service_descriptors_rpc_5foptions_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_rpc_5foptions_2eproto_getter() {
  return &descriptor_table_rpc_5foptions_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_rpc_5foptions_2eproto(&descriptor_table_rpc_5foptions_2eproto);
namespace flare {
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< int32_t >, 5, false>
  max_queueing_delay_ms(kMaxQueueingDelayMsFieldNumber, 0, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< int32_t >, 5, false>
  max_ongoing_requests(kMaxOngoingRequestsFieldNumber, 0, nullptr);

// @@protoc_insertion_point(namespace_scope)
}  // namespace flare
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
